# fly.toml app configuration file generated for bristolbe-backend on 2024-01-15T10:24:49+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bristolbe-backend"
primary_region = "cdg"

[build]
  dockerfile = "./Dockerfile"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
