#!/bin/bash

export PGUSER=postgres

cd migrations/db

psql -U postgres -f createdb.sql

export PGUSER=bristol
export SQITCH_PASSWORD=bristol

cd ..

bash sqitch_deploy

unset PGUSER
unset SQITCH_PASSWORD