#!/bin/bash

export PGUSER=postgres

cd ../migrations/db

psql -f createdb.sql

unset PGUSER

export SQITCH_USERNAME=bristol
export SQITCH_PASSWORD=bristol

cd ..

bash sqitch_deploy

unset SQITCH_USERNAME
unset SQITCH_PASSWORD